type-challenges/type-challenges

questions/6-hard-simple-vue/README.md, questions/6-hard-simple-vue/test-cases.ts
Added three cases:
```diff
+ // @ts-expect-error
+ this.firstname
+ // @ts-expect-error
+ this.getRandom()
```
This makes sure `data` or methods won't be able to be accessed too early.
```diff
+ // @ts-expect-error
+ this.data()
```
This makes sure `this` on `data` won't be the options itself.
```diff
+ getRandom() {
+   return Math.random()
+ },
...
+ alert(this.getRandom())
```
This makes sure one method can call another method.
=> feat(question): make "Simple Vue" stricter

questions/4-easy-pick/test-cases.ts
Pick<T, K> only accepts values for K when they are keys of T. The original tests didn't catch if this restriction was not respected.
Feel free to suggest a better approach to this test.
=> #7 - Validate if Pick blocks non-key values

questions/119-medium-replaceall/test-cases.ts
Sorry, my English is not good, but I try to describe the problem.
`119 - ReplaceAll`
> Implement `ReplaceAll<S, From, To>` which replace the all the substring `From` with `To` in the given string `S`
```ts
/* _____________ Your Code Here _____________ */
type ReplaceAll<S extends string, From extends string, To extends string> =  any
/* _____________ Test Cases _____________ */
import { Equal, Expect } from '@type-challenges/utils'
type cases = [
Expect<Equal<ReplaceAll<'foobar', 'bar', 'foo'>, 'foofoo'>>,
Expect<Equal<ReplaceAll<'foobarbar', 'bar', 'foo'>, 'foofoofoo'>>,
Expect<Equal<ReplaceAll<'t y p e s', ' ', ''>, 'types'>>,
Expect<Equal<ReplaceAll<'foobarbar', '', 'foo'>, 'foobarbar'>>,
Expect<Equal<ReplaceAll<'', '', ''>, ''>>,
]
```
The test case does not include use cases starting …
=> fix: ReplaceAll question test case is not complete

questions/12-medium-chainable-options/README.md
Fixed typo in `questions/12-medium-chainable-options/README.md`.
=> Fixed typo

questions/697-extreme-tag/test-cases.ts
See https://github.com/type-challenges/type-challenges/issues/713#issuecomment-765896244.
=> fix: #697 replacement of IsTrue/IsFalse that skip any with more accurate Equal

questions/869-extreme-distributeunions/test-cases.ts
In this pull request, checking for tuples (which are not in a fixed order) has been replaced with checking for original unions.
Solves checking should be independent of the order in which TypeScript turns unions into tuples (I checked these tests on my solution, they remained consistent).
=> fix(869): solves checking should be independent of implementation details

questions/645-medium-diff/template.ts
demo code causes `Duplicate identifier bug` in typescript playground
=> fix(Diff): remove demo code in template.ts

questions/1097-null-isunion/info.yml
A '#' character was left in the original new question form and the automation ignored the commented difficulty value.
=> Update info.yml to set difficulty of 1097-isunion

questions/898-easy-includes/test-cases.ts
This would invalidate solutions such as:
```typescript
type Includes<T extends readonly any[], U> = T extends [...any[], U] ? true : T extends [U, ...any[]] ? true : false;
```
=> Add test cases for element in between or at start

questions/898-easy-includes/test-cases.ts
The reasoning for adding this is because it invalidates the commonly answered:
```ts
type Includes<T extends readonly any[], U> = U extends T[number] ? true : false;
```
Which fails with the test case added.
=> Add another test case with objects

questions/1130-medium-replacekeys/test-cases.ts
=> Remove extra imports in `ReplaceKeys`

questions/459-medium-flatten/README.md
The generic argument passed by the Flatten type in the example is missing a closing bracket, causing the example to fail
=> The lack of the brackets

questions/7-easy-readonly/test-cases.ts
By default, `Readonly<T>` is **not** recursive. The current test method does not take this into account. Thus, the following (incorrect) answer would be accepted:
```ts
type MyReadonly<T> = {
readonly [A in keyof T]: MyReadonly<T[A]>
}
```ts
Adding a complex object into the test case would also test if this particular scenario is covered. It should fail if the user's answer is recursive.
=> Adds complex object in 7-easy-readonly test-case to check for recursiveness

questions/119-medium-replaceall/test-cases.ts
When I look for a better answer to `ReplaceAll`, I found some answers cannot pass extra test case, you can view detail [here](https://github.com/type-challenges/type-challenges/issues/1938#issuecomment-873426597).
=> chore: add test case for 'ReplaceAll'

utils/index.d.test.ts
👋 I was going through the exercises and noticed the `Alike` utility type didn't have an associated test case. Feel free to close this PR if it is unneeded.
=> test: Add test case for Alike util

questions/898-easy-includes/test-cases.ts
Hi, some solutions based on mapped types like
```
type Mapped<T extends readonly any[], U> = {
[k in T[number]]: true
}
```
contain an error, because the false or boolean are not included in the keys of the resulting type.
This test case will check it.
=> add test case for 898

questions/189-easy-awaited/test-cases.ts
Like the ```Awaited``` type in typescript 4.5 , we need to recursively unwrap Promise
=> fix: add text case for Awaited

questions/119-medium-replaceall/test-cases.ts
when `From` not exist in the given `S`
=> fix: add test case for #119 medium replaceall

questions/645-medium-diff/test-cases.ts
`type Diff<O, O1> = { [P in keyof O1 as P extends keyof O ? never : P]: O1[P] }`
can pass `Expect<Equal<Diff<Foo, Bar>, { gender: number }>>`
so we need add  `Expect<Equal<Diff<Bar,Foo>, { gender: number }>>` test case
=> fix: add test case for 645 medium diff

questions/4425-medium-greater-than/test-cases.ts
Until then, I can pass all test cases by simply determining whether `T extends U ? false : true`
=> fix: add a test case

questions/11-easy-tuple-to-object/info.yml
The label is related rather than tags. 
The project readme generate not correctly in "By Tags" section.
=> fix: update info.yml for tuple-to-object

questions/730-hard-union-to-tuple/test-cases.ts
I used this case and passed test, however, **it should not expected**, which `UnionToTuple<'a' | 'b'>` is `['a'|'b']`
```ts
type UnionToTuple<T> = [Exclude<T, undefined>]
```
So, I add new case to check Tuple **length**
Now, above case can not pass the test.
=> fix: add a test case to 730

.vscode/settings.json
I try to play type-challenges but...
Github Copilot learned many technics and copy and pasted code from here.
So GitHub Copilot is just spoiler on this repo. I think it should be disabled by default.
=> fix: disable copilot on vscode (spoiler)

.vscode/settings.json
Override global settings that might force semicolons.
=> chore: set explicitly removing semicolon in vscode workspace settings

questions/05153-medium-indexof/test-cases.ts, questions/05317-medium-lastindexof/test-cases.ts
添加一些类似于[Unique](https://github.com/type-challenges/type-challenges/blob/main/questions/05360-medium-unique/README.md)下的测试用例, 测试例如'1'与string, any等边界情况
=> enhance: improve test cases in 05153-medium-indexof and 05317-medium-lastindexof

questions/00011-easy-tuple-to-object/test-cases.ts, questions/00189-easy-awaited/test-cases.ts
Tuples can contain numbers and strings, so I added the test case, the generic type declaration of the existing answer also needs to be modified
=> add test-cases

questions/00296-medium-permutation/test-cases.ts
Add test case for union types of non-string types.
=> chore(00296-medium-permutation): improve test cases

questions/00956-hard-deeppick/test-cases.ts
All solutions using the trick of `UnionToIntersection<Union extends Union ? ... : never>` fail in this edge case.
The pattern is `DeepPick<Obj, 'a' | ''>` -> `UnionToIntersection<DeepPick<Obj, 'a'> | DeepPick<Obj, ''>>`
But there is a pitfall:
`UnionToIntersection<object | unknown>` -> `UnionToIntersection<unknown>` -> `unknown`
And in this challenge what we want is: 
`DeepPick<Obj, 'a' | ''>` -> `DeepPick<Obj, 'a'> & DeepPick<Obj, ''>` -> `object & unknown` -> `object`
A proper solution is [this one](https://github.com/type-challenges/type-challenges/issues/3294).
=> enhance: add a test case to 956-hard-deeppick

questions/03196-medium-flip-arguments/test-cases.ts
This question is to examine the function type, so the generic type must be specified as Function, so I added some ts-expect-error.
=> test: add ts-expect-error in 3196-flip-arguments

questions/01367-medium-remove-index-signature/test-cases.ts
The most commented answer(https://github.com/type-challenges/type-challenges/issues/3542) doesn't take into account the use of number or symbol as key. see [ts playground](https://tsplay.dev/NdADvm)
=> enhance: improve test case in 01367-medium-remove-index-signature

questions/00043-easy-exclude/test-cases.ts
If you use the built-in `Exclude`, users can see the answer
I modified it to the direct expected response
=> Modify `exclude` test expected response

questions/00462-extreme-currying-2/README.md
`curriedAdd(2)(3)(4)` should be nine, not eight.
=> Fix example result value from 462・Currying 2

questions/00191-medium-append-argument/test-cases.ts
The first argument must be a function.
=> feat: add test case to 00191-medium-append-argument

questions/00949-medium-anyof/test-cases.ts
Null and undefined are treated as false conditions.
=> enhance: add test case to 00949-medium-anyof

questions/00017-hard-currying-1/test-cases.ts
I think it would be better if we have a test case that curries a function with empty arguments.
=> enhance: add test cases of 00017-hard-currying-1

questions/02757-medium-partialbykeys/test-cases.ts
Because the description of this problem says that
> `K` specify the set of properties of `T`
So I think it would be better if we validate the `K` generic parameter.
=> enhance:  fix test case of 02757-medium-partialbykeys

questions/02759-medium-requiredbykeys/test-cases.ts
This challenge is very similar to 02757-medium-partialbykeys, I think the test-cases should also be consistent
reference：https://github.com/type-challenges/type-challenges/pull/17332
=> fix: update test-cases of 02759-medium-requiredbykeys

questions/03192-medium-reverse/test-cases.ts
```ts
type errors = [
// @ts-expect-error
Reverse<'string'>,
// @ts-expect-error
Reverse<{ key: 'value' }>,
]
```
=> feat(03192-medium-reverse)-add-error-cases

questions/00009-medium-deep-readonly/test-cases.ts
There currently is [a popular solution to challenge _00009 - Deep Readonly_](https://github.com/type-challenges/type-challenges/issues/187):
```ts
type DeepReadonly<T> = keyof T extends never
? T
: { readonly [k in keyof T]: DeepReadonly<T[k]> };
```
But [as explained here](https://stackoverflow.com/a/68693367), this answer does not cover cases where a value is a union of object types. On top of that, I also think using `keyof T extends never` to check for the function type is kind of hacky and definitely doesn't clearly express the intent of the code.
This is especially an eyesore when an equally concise and much more expressive solution with better coverage (i.e. using `extends Function ?`) already exists.
This pull request hopes to add a test case to expose the weakness of the popular …
=> Add a test case for unioned object type

questions/02257-medium-minusone/test-cases.ts
Managed to come up with [a solution that works for very large numbers](https://github.com/type-challenges/type-challenges/issues/21030). Thought I could include the largest of them that still worked.
Haha, let me know if you don't want the new test case to be included and I'll close the pull request.
=> 02257-medium-minusone: Add a test case with an absurdly large number

questions/08804-hard-two-sum/test-cases.ts
- Currently, all test cases are written s.t. all input elements are leq to the target number.
- If TwoSum is written to terminate and return false when an input element is greater than the target number, it will pass all existing test cases, resulting in a false negative.
- Example:
```
T extends [infer E extends number, ...infer Rest extends number[]]
? Subtract<U, E> extends never
? false
: (...processes Rest correctly...)
```
- The proposed addition tests TwoSum against a non-empty tuple with a head element that is greater than the target number.
See: 8804 - Two Sum (with explanation, new test case) #21260
=> test: fix false negative in 08804-hard-two-sum test cases

questions/00151-extreme-query-string-parser/test-cases.ts
- `Query String Parser` doesn't define how new entries with empty values should be handled if a duplicate key already exists in the parsed object. 
- There are two possible ways to handle this case.
- 1) merge `true` into tuple value for existing key
- 2) always override existing value with `true`
- This commit illustrates the first case.
See: 151 - Query String Parser (with explanation, new test cases) #21419
=> test: if duplicate key exists and new value is empty in 00151-extreme-query-string-parser 

questions/04518-medium-fill/test-cases.ts
- Currently, solutions that do not handle input s.t. `T["length"] <= Start <= End` by returning `T` can pass all test cases.
- See: #21503
```ts
// Example: `Fill<[1, 2, 3], true, 10, 20>` resolves to `never`, but passes all test cases.
type Fill<
T extends unknown[],
N,
Start extends number = 0,
End extends number = T['length'],
MStart extends number = Subtract<T["length"], Start> extends never ? T["length"] : Start,
MEnd extends number = Subtract<T["length"], End> extends never ? T["length"] : End,
M extends number|never = Subtract<MEnd, MStart>,
> = 
Subtract<End, Start> extends never
? T
: [...Pop<T, Subtract<T["length"], Start>>, ...Repeat<M, N>, ...Shift<T, End>]
// Fix: `Fill<[1, 2, 3], true, 10, 20>` correctly resolves to `[1, 2, 3]`
: [...Pop<T, Subtract<T["length"], MStart>>, …
```
=> test: fix false negative in 04518-medium-fill when start, end are both out of bounds and not inverted

questions/00274-extreme-integers-comparator/test-cases.ts
1. The existing test cases all compare integers of equal lengths. 
2. Large inputs aren't covered. Added test cases for `Number.MAX_SAFE_INTEGER, Number.MIN_SAFE_INTEGER`.
See: #21601
=> test: 00274-extreme-integers-comparator test inputs of different lengths, large numbers

questions/04425-medium-greater-than/test-cases.ts
This test case with `<10, 9>` is different from the `<111, 11>` in the way that it has arguments of different lengths, AND a lower number has greater digits. The [solution I've recently posted to this problem](https://github.com/type-challenges/type-challenges/issues/21721) appeared to have this bug, and it had been figured out only thanks to @Yueleng
Also, I've added a test case with a big number (within a safe Number range) that I've noted some other solutions are failing on
=> 4425 - GreaterThan - add test case

questions/02693-medium-endswith/test-cases.ts
```ts
type last<T> = T extends `${infer L}${infer R}` ? (R extends "" ? L : last<R>) : T;
type EndsWith<T extends string, U extends string> = last<T> extends last<U> ? true : false
```
Previous cases cannot be overwritten
=> Endswith update test-cases.ts

questions/09286-medium-firstuniquecharindex/test-cases.ts
Crashes at least one posted solution: https://github.com/type-challenges/type-challenges/issues/22117 I didn't check others - I assume it can be a popular misslooked edge-case
=> 9286 - FirstUniqueCharIndex - add a test case

questions/00015-medium-last/info.yml, questions/00016-medium-pop/info.yml, questions/00017-hard-currying-1/info.yml, questions/00018-easy-tuple-length/info.yml
Fixes https://github.com/type-challenges/type-challenges/issues/25615
This is happening because there is no `difficulty` in the `info.yml` file for questions 00015, 00016, 00017 and 00018.
=> add difficulty for questions - 00015, 000016, 00017 and 00018, preventing undefined filename in playground folder

questions/00015-medium-last/test-cases.ts
At the moment it is possible to write a naive backwards solution that covers both existing test cases, but overall would be flawed.
```ts
type Last<T extends any[]> = T extends [infer _Head, ...infer Tail]
? Tail['length'] extends 1
? Tail[0]
: Last<Tail>
: never
...
// Both cases pass
type cases = [
Expect<Equal<Last<[3, 2, 1]>, 1>>,
Expect<Equal<Last<[() => 123, { a: string }]>, { a: string }>>,
]
```
This PR adds a case where the array contains only a single element.
=> Add new test case for challenge 00015-medium-last

questions/00533-easy-concat/test-cases.ts
The test case didn't provide a negative path, but it's better to have one.
I also added one test case to check if the solution can take in readonly tuples.
=> 533 - add more test cases

.gitignore, README.md, scripts/generate-play.ts
Fixes: https://github.com/type-challenges/type-challenges/issues/27365
Fixes: https://github.com/type-challenges/type-challenges/issues/27420
This PR will allow `generate-play` script to do these things
1. `pnpm generate -K` will not override files that users have edited
2. both `pnpm generate` and `pnpm generate -K` will generate a structured playground, categorized by difficulty
```
playground
├── warm
├── easy
├── medium
├── hard
└── extreme
```
=> feat: generate-play can structurize playground and preserve changes

questions/00459-medium-flatten/test-cases.ts
with this test case, this kind of solution will throw an error
including the second-highest voted answer <https://github.com/type-challenges/type-challenges/issues/511>
=> feat: add test case to 459

questions/10969-medium-integer/test-cases.ts
These test cases can play a part when players parse the number bit by bit
=> test: add more test cases to 10969-medium-integer

questions/04037-hard-ispalindrome/test-cases.ts
There are 2 types of palindrome, odd one, which has been already covered, and even one, which is added by this PR.
=> test: add essential test cases to 4037-IsPalindrome

package.json
I don't know why but esno 0.16.3 does not accept "import" statement.
Tweaking tsconfig, like setting "module" to "esnext", did not help.  
Upgrading to esno v4 resolved this issue in my env, MacOS 14.2, Node v20.5.1, vscode 1.85.1.
=> chore: upgrade esno

questions/00612-medium-kebabcase/README.ja.md
In Japanese, we found an error in the description of homonyms in kanji, which has been corrected.
=> chore: typo questions/00612-medium-kebabcase/README.ja.md

questions/30301-medium-isodd/test-cases.ts
The new test cases cover some interesting failure modes, such as false negatives for single-digit numbers, and false positives for fractional numbers and scientific-notation.
=> Expand test cases for `30301-IsOdd`

questions/21220-medium-permutations-of-tuple/README.md
The README.md for the challenge [21220](https://github.com/type-challenges/type-challenges/tree/main/questions/21220-medium-permutations-of-tuple) includes a multi-line comment, which causes the associated [playground](https://tsch.js.org/21220/play) to break. This PR fixes the issue by replacing the multi-line comment with multiple single-line comments.
=> 21220: Update multi-line comment to single-line comments

questions/00003-medium-omit/test-cases.ts
I think should add a new test case to the 00003-medium-omit test file.
```typescript
Expect<Equal<Expected3, MyOmit<Todo1, 'description' | 'completed'>>>
interface Todo1 {
readonly title: string
description: string
completed: boolean
}
interface Expected3 {
readonly title: string
}
```
The previous test cases do not cover the scenario where the MyOmit generic might cause loss of modifiers for non-omitted properties. 
For example, the following generic can pass the previous test cases.However, it can cause the loss of modifiers for non-omitted properties.
```typescript
export type MyOmit<T, K extends keyof T> = {
[P in myExclude<keyof T, K>]: T[P]
}
type myExclude<T, K> = T extends K ? never : T;
````
Then, I found that TypeScript's Omit<T, K> generic does not cause the loss of modifiers …
=> test: add a test case to 00003-medium-omit

questions/00462-extreme-currying-2/test-cases.ts
The first test case crashes:
https://github.com/type-challenges/type-challenges/issues/18047 https://github.com/type-challenges/type-challenges/issues/22172 https://github.com/type-challenges/type-challenges/issues/16231 https://github.com/type-challenges/type-challenges/issues/13943 https://github.com/type-challenges/type-challenges/issues/13669 https://github.com/type-challenges/type-challenges/issues/8272 https://github.com/type-challenges/type-challenges/issues/3747 https://github.com/type-challenges/type-challenges/issues/761
The second test case crashes:
https://github.com/type-challenges/type-challenges/issues/15988 https://github.com/type-challenges/type-challenges/issues/6835 https://github.com/type-challenges/type-challenges/issues/5342 …
=> fix: 462 - Curring 2 - add a test cases

questions/00268-easy-if/test-cases.ts
I've added the test case that covers a union of `true | false` (also known as a `boolean`):
```typescript
Expect<Equal<If<boolean, 'a', 2>, 'a' | 2>>
```
Without this test case, the following (incorrect) solution is accepted:
```typescript
type If<C extends boolean, T, F> = true extends C ? T : F;
// X is 'a'
type X = If<boolean, 'a', 2>
```
Flipping the `extends` condition (as done in the most popular solution: https://github.com/type-challenges/type-challenges/issues/279) behaves as expected:
```typescript
type If<C extends boolean, T, F> = C extends true  ? T : F;
// X is 'a' | 2
type X = If<boolean, 'a', 2>
```
=> test: Add test case for `boolean` in 268-If 

questions/00189-easy-awaited/test-cases.ts
My proposal is to remove the test case that expects an error when providing `number` as argument. 
The original `Awaited<T>` also accepts primitive types, does not throw an error and simply returns the primitive. You can find the type in the [original TypeScript Repository](https://github.com/microsoft/TypeScript/blob/af3a61fe4487a92d59f9479aa4249d897b91af14/src/lib/es5.d.ts#L1545).
A solution to the challenge without this test: 
```ts
type MyAwaited<T> = 
T extends PromiseLike<infer Val> 
? MyAwaited<Val> 
: T
```
Compare that to a solution that goes the extra length to make the test pass:
```ts
type MyAwaited<T extends PromiseLike<any>> = 
T extends PromiseLike<infer Val> 
? Val extends PromiseLike<unknown>
? MyAwaited<Val> 
: Val
: never
```
I'm not removing this test to make the …
=> test: remove unnecessary test-case from 00189-easy-awaited

questions/05140-medium-trunc/test-cases.ts
The case Math.trunc('-.3') is valid but is not covered on Trunc tests cases.
Having a test for Trunc<'-.3'> will force to add another check in the implementation to cover that specific case. Not more difficult but just a little twist.
=> feat: add test case for '-.3' in 05140-Trunc

questions/27133-medium-square/test-cases.ts
I noticed that some solutions treat `100` as a special case. I think it shouldn’t be treated as such, so I added a test case with `101` .
=> test(27133-medium-square): add test cases

questions/00015-medium-last/test-cases.ts
The last element of the empty array is never.
```
Expect<Equal<Last<[]>, never>>
```
=> test: add empty array case in 00015

questions/31824-hard-length-of-string-3/test-cases.ts
The `Gened` type in the "Length of String 3" test cases produces the following error:
This PR fixes it by inferring the digits from the input recursively instead of doing it all at once.
=> fix: fix length of string 3 tests

questions/02257-medium-minusone/test-cases.ts
in this challenge (#02257).
the describe is
> Given a number (always positive) as a type. Your type should return the number decreased by one.
so it should be a number more then zero.
but in cases `Equal<MinusOne<0>, -1>` happened .
i think should remove it.
=> case(#02257):remove zero case

questions/30301-medium-isodd/test-cases.ts
add Test Case to [IsOdd](https://github.com/type-challenges/type-challenges/blob/main/questions/30301-medium-isodd/README.md)
There is already a test case for `3e23`, which is always even because it represents 3×10^23.
However, in the case of `3e0`, it equals 3×10^0=3×1=3, which is odd.
In other words, when the exponent is 0, we need to check the number before `e` to determine whether it is odd or even.
=> case(IsOdd): add 3e0 case

questions/00274-extreme-integers-comparator/test-cases.ts
Added a pattern for comparing decimals. 
The policy for solving is that you can compare decimals by breaking them down before and after the decimal point. If there is a decimal point, you can look at the decimal point by recursing the Comparator only when the numbers before the decimal point are the same.
=> case(Integers Comparator): add consider decimal

package.json, pnpm-lock.yaml, scripts/generate-play.ts
Hello @antfu,
This PR replaces `picocolors` with a better alternative `ansis` that supports both CJS and ESM.
Ansis supports chained syntax for clean and readable code.
=> feat: replace picocolors with ansis

questions/25747-hard-isnegativenumber/info.yml
This PR replaces `template literal` with `template-literal` for consistency and will fix the duplicate tag generation issue.
=> fix: correct tag to `template-literal`
