questions/2-medium-return-type/test-cases.ts

add test case for arity-genericity to 2 - Get Return Type

feat: add test case

---

questions/89-hard-required-keys/test-cases.ts

The Playground also needs to be fix.
https://tsch.js.org/89/play

fix: typo in question 89

---

questions/90-hard-optional-keys/test-cases.ts

The Playground also needs to be fix.
https://tsch.js.org/90/play

fix: typo in question 90

---

questions/18-easy-tuple-length/README.md

remove redundant typeof  and const assertion

---

questions/11-easy-tuple-to-object/README.ja.md
questions/11-easy-tuple-to-object/README.md
questions/11-easy-tuple-to-object/README.zh-CN.md
questions/4-easy-pick/README.ja.md

chore: fix typo & add typeof

---

questions/10-medium-tuple-to-union/README.ja.md
questions/2-medium-return-type/README.ja.md
questions/3-medium-omit/README.ja.md
questions/8-medium-readonly-2/README.ja.md
questions/9-medium-deep-readonly/README.ja.md

Improved Japanese translation quality.

i18n: improved Japanese translation quality

---

questions/6-hard-simple-vue/README.md

docs: fix typo

---

questions/62-medium-type-lookup/README.md

👋 [Type Lookup](https://github.com/type-challenges/type-challenges/blob/master/questions/62-medium-type-lookup/README.md)
😃 `type MyDog = LookUp<Cat | Dog, 'dog'>`
😭 `const MyDog = LookUp<Cat | Dog, 'dog'>`
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMJzMg3gKGcsATwAcIAuZAcgQ0r2QCMoIIATAZwsoEEHD32oYHBCVkAHyoBlABYB7KGBlxgUMZMqoArlAA26qgCEIIAOZx9OAL44coSLEQoAInNPZ6RUl1Zu6+JhYOLgAJOS0QVgNKQyhgMDARQmjDLV1dX1MUuQAPaH9kBDldBS4mOQB3UQkqCpl4iGiGXUQAazobHC8UABk5OVaAVWIAHkGAGmQAFWQIHMhI9mR2MDizAD5kAF4PfABtAGlkUGmAXQpB2fmTDmwCEnJp5CtkAH5kS4oQCAA3aGs9lNTrZusgALKEVzuHZ9AbDEboTCSKGTSiZSjrWwAeixhTkIBW4Mhbm2yFhQ1GiJqKKo6PWQA

🤠 convert value to type

---

utils/index.d.test.ts

feat(utils): add more test cases

---

questions/191-medium-append-argument/README.md

In the https://dev.to/macsikora/advanced-typescript-exercises-question-4-495c, it was about appending argument A as a first one, but now the question requires inserting a new argument as a last one.

fix: typo 191

---

.github/ISSUE_TEMPLATE/0-answer.md

fix a typo in file 0-answer.md of ISSUE_TEMPLATE.

chore: fix issue template typo

---

README.md
README.zh-CN.md
questions/106-medium-trimleft/info.yml
questions/108-medium-trim/info.yml
questions/110-medium-capitalize/info.yml
questions/112-hard-capitalizewords/info.yml
questions/114-hard-camelcase/info.yml
questions/116-medium-replace/info.yml
questions/119-medium-replaceall/info.yml
questions/147-hard-c-printf-parser/info.yml
questions/151-extreme-query-string-parser/info.yml
questions/216-extreme-slice/info.yml
questions/270-hard-typed-get/info.yml
questions/274-extreme-integers-comparator/info.yml
questions/296-medium-permutation/info.yml
questions/298-medium-length-of-string/info.yml
questions/300-hard-string-to-number/info.yml

feat: support ts 4.1

---

README.md

Just wanted to start out by saying this is a great project. 
I noticed while reading the docs that there were a few grammatical/structural errors in the text so I thought I'd fix the typos I found

Fix grammatical structure in README text

---

README.ja.md

Translate `Now supports TypeScript 4.1 🎉`

chore: update

---

questions/106-medium-trimleft/README.ja.md
questions/108-medium-trim/README.ja.md
questions/110-medium-capitalize/README.ja.md
questions/112-hard-capitalizewords/README.ja.md
questions/114-hard-camelcase/README.ja.md

Added Japanese translation of new questions.

Add Japanese translation

---

questions/119-medium-replaceall/test-cases.ts

fix: add suite case to not allow recursive replacing in #119

---

questions/459-medium-flatten/README.ja.md
questions/531-medium-string-to-union/README.ja.md
questions/599-medium-merge/README.ja.md

・459-medium-flatten
・531-medium-string-to-union
・599-medium-merge

Add README.ja.md

---

questions/898-easy-includes/README.md
questions/949-medium-anyof/README.md

* Syntax highlight
https://github.com/type-challenges/type-challenges/tree/master/questions/949-medium-anyof
↓
https://github.com/technote-space/type-challenges/tree/chore/syntax_highlight/questions/949-medium-anyof
* Syntax highlight
* Add new lines around `For example`
https://github.com/type-challenges/type-challenges/tree/master/questions/898-easy-includes
↓
https://github.com/technote-space/type-challenges/tree/chore/syntax_highlight/questions/898-easy-includes

Syntax highlight

---

questions/898-easy-includes/test-cases.ts

* Remove unused imports.
* Add one more true case where the target element is not the first one.

fix(898): update test cases

---

questions/1130-medium-replacekeys/README.md

the comment doesn't match the test case, `flag: number` should not be omited

fix: comments in ReplaceKeys

---

questions/898-easy-includes/test-cases.ts

When I looked at the solutions to question 898, most of them pass all the test cases but that's actually not true.
such as this solution:  #1915

Add test case for 898

---

questions/1383-hard-camelize/README.md
questions/1383-hard-camelize/template.ts
questions/1383-hard-camelize/test-cases.ts

Hello, I find 1383 no test case, so i'm try to add.

Add test case for 1383

---

questions/189-easy-awaited/info.yml
questions/189-easy-awaited/template.ts
questions/189-easy-awaited/test-cases.ts

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements

fix: built-in Awaited conflict

---

questions/116-medium-replace/test-cases.ts

the string `From`  not exist  in the given string `S`

fix: add test case for #116 medium replace

---

.github/workflows/pr-merged.yaml

I found In some actions the "EndBug/add-and-commit@v4" doen't work correctly,so some readme doesn't generate correctly.

fix: update pr-merged.yaml

---

README.md
README.zh-CN.md
TODOs.md

Makes READMEs more readable and a few corrections with indentation/spelling & grammar

docs: fix indentation and add closing p tag

---

README.md

chore: indent image tag

---

scripts/actions/issue-pr.ts

This action doesn't consider locale ja, so [this issue](https://github.com/type-challenges/type-challenges/issues/4260)  has parse error.

fix: fix issue-pr locale error for ja

---

questions/4-easy-pick/README.ja.md
questions/4-easy-pick/README.ko.md
questions/4-easy-pick/README.md
questions/4-easy-pick/README.zh-CN.md
scripts/locales.ts
scripts/locales/ko.json

Hello. I just translated the challenge "Pick" to Korean. 
Please note that this is my first contribution. If this is correct, I will continue to translate other challenges.

Korean Translation of challenge "Pick"

---

questions/5117-medium-without/README.md
questions/5117-medium-without/README.zh-CN.md
questions/5153-medium-indexof/README.md
questions/527-medium-append-to-object/README.md
questions/9-medium-deep-readonly/README.md

Fixed typos of some questions.

fix: typos of some questions

---

README.md

Added a talk from @gvergnaud about type level programming in typescript. 
This is a very good talk that covers all the basics required to solve type challenges.

Added talks sections

---

questions/6-hard-simple-vue/test-cases.ts

The property of `data` function can be accessed in `methods`

enhance(6): update 6 test case

---

questions/14-easy-first/test-cases.ts

Add two test cases of `@ts-expect-error`

enhance: add test cases to 14-easy-first

---

questions/20-medium-promise-all/README.ja.md
questions/20-medium-promise-all/README.md
questions/20-medium-promise-all/README.zh-CN.md

The parameters in the example are constants, I think the result corresponding to promise2 should be 42.

doc: 20-medium-promise-all

---

utils/index.d.test.ts

fix: eslint error tip

---

README.md

Hoping to have this as a recommendation to other developers who want an opinionated guide on how to use TypeScript effectively.
I'm just about finishing it, and it was while reading it that I realized that type programming must exist, and just as with normal programming, I would need challenges to master the learnings from the book.
I think other developers will find it very useful as an opinionated resource to augment the official handbook.

Add a book recommendation for reading

---

questions/9-medium-deep-readonly/test-cases.ts

Hi, 
The current test case cannot cover array fields.
Here is [typescript playground example](https://www.typescriptlang.org/play?#code/PQKgUABBCcELQQCIFNkAcICVkEMAmA9gHYA2AnpPHNTZQEZkQCCRALgBbGMBiArhAAoAAjjYAzXgEoIAYgC2yPAEtec2QCdchUoxkE6AK2QBjVnADWyMgGdZeVGkqUZLiAEVeya6yXEnUAEk5NBJkBTYIHAgAc2QiZHUlYwgAAxR0bHxicgAeABUAPhSIAHd2JPYIORxLCGQANwTGNBx1HAVWBIgCMUiibsMTVng+vAglVltrXjo4fSNTW01jXnVrJUbyEc0snQA6fwgATQJ+Y1FI62mFCA4cYZLkSM1unQh7HBIlImjSicqAPKDRbjfocJS2YzsT6hH7IPbMdRtGwAGggfCIpl8RGsaIAwiQcFcvKMINYCK9nk8iBT4opbhTWDUnt9WBTjMR1vY2j5iAiABIER6NdRosinCDnfreJQkEiS6FyuKxCDi1Zk5AkXoMSUEEXfX7KMRiBJxYbnawkolVUSMa1oAhXJR0UIHKCUbgEdR1AAe7RCyEOKWDk0orDIaCeAA0IABeCAAbwglCgPoAXInk1Bs5EMwBGFPZugZgDk5RLhYAvoWyKX2FYK1Bq+6oOHIxAAKI+yOmenxpOFnbaLbpzOFqBD7J2-PjiCTt7FiBlpSN7PN7Pzra1pf1sglrMQddhiNPPIEQhxpAOTL …

add test case to 9-medium-deep-readonly

---

questions/08767-medium-combination/test-cases.ts

update type name in test case that same to template and title

typo(8767): type name in test case

---

questions/00949-medium-anyof/README.md
questions/00949-medium-anyof/README.zh-CN.md

docs(questions): add Chinese translation

---

questions/04425-medium-greater-than/README.md
questions/04425-medium-greater-than/test-cases.ts

compare numbers of diffrent length

enhance: improve test cases in 04425-medium-greater-than

---

questions/08767-medium-combination/README.md
questions/08767-medium-combination/info.yml
questions/08767-medium-combination/test-cases.ts

https://github.com/type-challenges/type-challenges/issues/9089
the unsorted result seems vary from each other, so make it more universal

fix: result

---

README.ja.md
README.ko.md
README.md
README.zh-CN.md
TODOs.md

contributors graph generated by contrib.rocks

feat: contributors graph

---

questions/03188-medium-tuple-to-nested-object/test-cases.ts
questions/03192-medium-reverse/test-cases.ts
questions/03196-medium-flip-arguments/test-cases.ts
questions/03243-medium-flattendepth/test-cases.ts
questions/03376-medium-inordertraversal/test-cases.ts
questions/04484-medium-istuple/test-cases.ts

[fix: remove useless import](https://github.com/type-challenges/type-challenges/commit/d5856c75d21cf9c086af6283fa0e4e601a9f3019)
[fix(4484): add a test-case](https://github.com/type-challenges/type-challenges/commit/c37fabddb0c9dbba41ba7cab7048dcc133f58558)

fix: remove useless import and add test-case

---

utils/index.d.test.ts

Add test cases to Equal

---

questions/04179-medium-flip/README.md

The f here should be capitalized

The f here should be capitalized in READEME

---

questions/00300-hard-string-to-number/test-cases.ts

add mixed number and other characters' situation

enhance: add a test case to 00300-hard-ToNumber

---

questions/00545-hard-printf/test-cases.ts

Add test cases similar to [147-hard-c-printf-parser](https://github.com/type-challenges/type-challenges/tree/main/questions/00147-hard-c-printf-parser)([Playground](https://tsch.js.org/147/play)).

enhance: add more test cases to 545-hard-printf

---

questions/00949-medium-anyof/README.zh-CN.md

fix: AnyOf Chinese README.md spelling error

---

questions/01097-medium-isunion/test-cases.ts

01097-medium-isunion add a test case

01097-medium-isunion add test case

---

questions/01042-medium-isnever/template.ts

Add missing generic for [questions/01042-medium-isnever/template.ts](https://github.com/type-challenges/type-challenges/tree/main/questions/01042-medium-isnever)

fix: add missing generic

---

questions/00016-medium-pop/README.zh-CN.md

Docs: fix a chinese translate error of 16 Pop

---

questions/00016-medium-pop/test-cases.ts

feat: add test case to questions/00016-medium-pop

feat: add test case to questions/00016-medium-pop

---

questions/03062-medium-shift/test-cases.ts

add critical condition test cases for 03062-medium-shift.

opt: add test cases for 03062-medium-shift

---

questions/17973-medium-deepmutable/README.md
questions/17973-medium-deepmutable/README.zh-CN.md

docs: update deepMutabl README

---

questions/00697-extreme-tag/test-cases.ts

I fixed variables in an assignment checking in the question of `Tag`.

fix Tag test cases

---

questions/02257-medium-minusone/test-cases.ts

`Expect<Equal<MinusOne<0>, -1>>`

feat(02257-medium-minusone): add one test case

---

questions/18220-medium-filter/template.ts
questions/18220-medium-filter/test-cases.ts

18220-medium-filter: Conform with other challenges

---

questions/00151-extreme-query-string-parser/test-cases.ts

For now there is no test with adding duplicate value to array
So I have created some

#21566 query string parser: tests with adding duplicate value to array

---

questions/06228-extreme-json-parser/info.yml

Sorry about this. I renamed but GitHub can't redirect this link to my personal page. :(

fix: author info

---

questions/00008-medium-readonly-2/test-cases.ts

Added a new test case to readonly-2.
While going through some solutions, I found that some people's answers failed when I made this change in the test case so having this additional test can be useful.

enhance: add a new test case to readonly-2

---

questions/09384-hard-maximum/README.md

Fix some typos present in the challenge description.

Update README.md for 09384-hard-maximum

---

questions/08804-hard-two-sum/README.md

Added examples of question 08804, "two-sum"

docs: update twoSum README

---

questions/21106-medium-zu-he-jian-lei-xing-combination-key-type/template.ts
questions/21106-medium-zu-he-jian-lei-xing-combination-key-type/test-cases.ts

fix: function in test case is missing args (question 21106)

---

questions/05310-medium-join/test-cases.ts

Added an edge case for empty tuple

test: add test case for 5310

---

questions/02946-medium-objectentries/test-cases.ts

with this test case，some solutions will be wrong
including the top votes answer: https://github.com/type-challenges/type-challenges/issues/14052

feat: add test case to 2946

---

scripts/generate-play.ts

Looks like the script cannot generate new quizes, i.e not in cache and not in the playground, in `keep-changes` mode.
This PR fixes it.

fix: generate -K should generate new quizes

---

questions/27958-medium-checkrepeatedtuple/README.md
questions/27958-medium-checkrepeatedtuple/README.zh-CN.md
questions/27958-medium-checkrepeatedtuple/info.yml

docs: add README.md for CheckRepeatedTuple

---

questions/00055-hard-union-to-intersection/README.ja.md
questions/00055-hard-union-to-intersection/README.md
questions/00055-hard-union-to-intersection/README.zh-CN.md

Union2Intersection -> UnionToIntersection

fix typo in question 55

---

scripts/generate-play.ts

Fixes: https://github.com/type-challenges/type-challenges/issues/28299

fix: generate playground should skip questions with missing locale

---

README.md

@GitMurf in  https://github.com/type-challenges/type-challenges/issues/21338#issuecomment-1638542116 made a great point re: adding this to the main readme.
I looked around to make sure this isn't generated from elsewhere and it seems like the update script just looks at a markdown comment to know where to update things so hopefully I updated the right place :)

docs: include MiTS video solutions

---

pnpm-lock.yaml
questions/02822-hard-split/test-cases.ts

I think this makes this challenge a bit more interesting (and I can confirm that there is a solution to it). Please feel free to correct me where I did something wrong or left somethings out.

feat: add multi-character separator test cases to Split challenge

---

questions/18142-medium-all/test-cases.ts

with this case,some solution will be wrong.
such like: [#22538](https://github.com/type-challenges/type-challenges/issues/22538)

feat: add test case to 18142

---

questions/13580-hard-replace-union/test-cases.ts

https://github.com/type-challenges/type-challenges/issues/28792

feat(question): add empty test branch

---

README.ko.md

- add 1 seminar link in ko readme
- The link to the seminar i've added deals with looking at the grammar of type scripts from the perspective of sets

docs: add 1 seminar link in ko readme

---

site/index.html
site/style.css

Improve responsiveness and HTML refactoring

docs: improve website

---

questions/00015-medium-last/test-cases.ts
questions/09898-medium-zhao-chu-mu-biao-shu-zu-zhong-zhi-chu-xian-guo-yi-ci-de-yuan-su/test-cases.ts

add some test cases to 8989
```ts
Expect<Equal<FindEles<[1, 2, number]>, [1, 2, number]>>
Expect<Equal<FindEles<[1, 2, number, number]>, [1, 2]>>
```

test: add some test cases to 8989

---

questions/27958-medium-checkrepeatedtuple/test-cases.ts

test(27958-medium-checkrepeatedtuple): add test cases

---

questions/35252-medium-isalphabet/README.ja.md

Added README.ja.md to 35252-medium-isalphabet

---

questions/03062-medium-shift/README.ja.md

Addition of Japanese translation

Created README.ja.md in 03062-medium-shift

---

scripts/readme.ts
scripts/translate.ts

refactor: remove unnecessary cast
